RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # No Color

# RUNNING CHECKS BACKEND
echo -e "${RED}RUNNING CHECKS BACKEND${NC}"

# RUNNING CHECKS FRONTEND 
echo -e "${GREEN}RUNNING CHECKS FRONTEND${NC}"

# RUNNING CHECKS VERSION 
echo -e "${YELLOW}RUNNING CHECKS VERSION${NC}"

# CHECK EXEC SCRIPTS 
echo -e "${BLUE}CHECK EXEC SCRIPTS${NC}"

# UNIT TESTS
echo -e "${MAGENTA}RUNING UNIT TESTS FRONT${NC}"

# UNITEST 
echo -e "${CYAN}RUNNING UNITEST BACK${NC}"

# LINT 
echo -e "${WHITE}LINT${NC}"

# BUILD 
echo -e "${GREEN}STARTING BUILD${NC}"
